In [51]:
import numpy as np
import pandas as pd
from sklearn import datasets as ds
from sklearn.linear_model import TweedieRegressor, LinearRegression
from sklearn.tree import DecisionTreeRegressor
import os
import json
import pickle

In [10]:
X = ds.load_boston().data
y = ds.load_boston().target

In [24]:
js = json.dumps({"model": "linreg", "X": X.tolist(), "Y": y.tolist()})

with open("test1.json", "w") as outfile:
    outfile.write(js)

In [25]:
js = json.dumps({"model": "tree", "X": X.tolist(), "Y": y.tolist(), "hyperparams":{"max_depth": 6, "min_samples_split": 5}})

with open("test2.json", "w") as outfile:
    outfile.write(js)

In [29]:
js = json.dumps({"X": X[:20].tolist(), "action": "predict"})

with open("test3.json", "w") as outfile:
    outfile.write(js)

In [59]:
js = json.dumps({"model": {"id": 1}, "X": X[:100].tolist(), "Y": y[:100].tolist()})

with open("test4.json", "w") as outfile:
    outfile.write(js)

## Тесты

In [44]:
with open(f"../models/{os.listdir('../models')[0]}", 'rb') as handle:
            model = pickle.load(handle)

C:\Users\Kirill\anaconda3\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator LinearRegression from version 1.1.2 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(


In [48]:
LinearRegression().fit(X, y).predict(X[:20])

array([30.00384338, 25.02556238, 30.56759672, 28.60703649, 27.94352423,
       25.25628446, 23.00180827, 19.53598843, 11.52363685, 18.92026211,
       18.99949651, 21.58679568, 20.90652153, 19.55290281, 19.28348205,
       19.29748321, 20.52750979, 16.91140135, 16.17801106, 18.40613603])

In [49]:
model.predict(X[:20])

array([30.00384338, 25.02556238, 30.56759672, 28.60703649, 27.94352423,
       25.25628446, 23.00180827, 19.53598843, 11.52363685, 18.92026211,
       18.99949651, 21.58679568, 20.90652153, 19.55290281, 19.28348205,
       19.29748321, 20.52750979, 16.91140135, 16.17801106, 18.40613603])

In [50]:
with open(f"../models/{os.listdir('../models')[1]}", 'rb') as handle:
            model = pickle.load(handle)

C:\Users\Kirill\anaconda3\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DecisionTreeRegressor from version 1.1.2 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(


In [53]:
DecisionTreeRegressor().fit(X, y).predict(X[:20])

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2])

In [54]:
DecisionTreeRegressor(max_depth=6, min_samples_split=5).fit(X, y).predict(X[:20])

array([23.46666667, 20.76598639, 34.544     , 34.544     , 34.544     ,
       28.7       , 20.76598639, 22.1       , 16.9125    , 16.9125    ,
       16.9125    , 20.76598639, 22.96666667, 20.76598639, 20.76598639,
       20.76598639, 23.85714286, 19.40833333, 20.76598639, 20.76598639])

In [55]:
model.predict(X[:20])

array([23.46666667, 20.76598639, 34.544     , 34.544     , 34.544     ,
       28.7       , 20.76598639, 22.1       , 16.9125    , 16.9125    ,
       16.9125    , 20.76598639, 22.96666667, 20.76598639, 20.76598639,
       20.76598639, 23.85714286, 19.40833333, 20.76598639, 20.76598639])

In [60]:
DecisionTreeRegressor(max_depth=6, min_samples_split=5).fit(X[:100], y[:100]).predict(X[:20])

array([24.25      , 21.1       , 33.7       , 33.7       , 35.5       ,
       29.3       , 23.18888889, 27.1       , 16.25      , 18.84285714,
       15.26666667, 18.84285714, 20.85      , 20.5       , 19.4       ,
       20.5       , 22.85      , 17.575     , 19.7       , 18.55      ])

In [61]:
with open(f"../models/{os.listdir('../models')[1]}", 'rb') as handle:
            model = pickle.load(handle)
model.predict(X[:20])

C:\Users\Kirill\anaconda3\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DecisionTreeRegressor from version 1.1.2 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(


array([24.25      , 21.1       , 33.7       , 33.7       , 35.5       ,
       29.3       , 23.18888889, 27.1       , 16.25      , 18.84285714,
       15.26666667, 18.84285714, 20.85      , 20.5       , 19.4       ,
       20.5       , 22.85      , 17.575     , 19.7       , 18.55      ])